<?php

$GLOBALS['MD_ICONS'] = [
    'article.gif'           => 'library_books',
    'bootstrap.png'         => 'format_bold',
    'css.gif'               => 'brush',
    'cut.gif'               => 'content_cut',
    'copy.gif'              => 'content_copy',
    'delete.gif'            => 'delete',
    'edit.gif'              => 'edit',
    'group.gif'             => 'people_outline',
    'header.gif'            => 'settings',
    'invisible.gif'         => 'visibility_off',
    'layout.gif'            => 'web',
    'mgroup.gif'            => 'people',
    'modules.gif'           => 'extension',
    'show.gif'              => 'info',
    'sizes.gif'             => 'collections',
    'su.gif'                => 'exit_to_app',
    'theme_export.gif'      => 'cloud_download',
    'visible.gif'           => 'visibility',

    // '1cl.gif',
    // '1rw.gif',
    // '2cll.gif',
    // '2clr.gif',
    // '2rwf.gif',
    // '2rwh.gif',
    // '3cl.gif',
    // '3rw.gif',
    // 'about.gif',
    // 'above.gif',
    // 'admin_.gif',
    // 'admin.gif',
    // 'alias.gif',
    // 'all_big.gif',
    // 'all.gif',
    // 'article_.gif',
    // 'article.gif',
    // 'articles_.gif',
    // 'articles.gif',
    // 'back.gif',
    // 'below.gif',
    // 'cache.gif',
    // 'changelog.gif',
    // 'clipboard.gif',
    // 'collapse.gif',
    // 'copychilds_.gif',
    // 'copychilds.gif',
    // 'copy_.gif',
    // 'cssimport.gif',
    // 'current.gif',
    // 'cut_.gif',
    // 'db.gif',
    // 'deleteAll.gif',
    // 'delete_.gif',
    // 'demagnify.gif',
    // 'diff_.gif',
    // 'diff.gif',
    // 'diffTemplate_.gif',
    // 'diffTemplate.gif',
    // 'down.gif',
    // 'drag.gif',
    // 'edit_.gif',
    // 'editor_.gif',
    // 'editor.gif',
    // 'error_403_1.gif',
    // 'error_403.gif',
    // 'error_404_1.gif',
    // 'error_404.gif',
    // 'error.gif',
    // 'error.png',
    // 'expand_.gif',
    // 'expand.gif',
    // 'featured_.gif',
    // 'featured.gif',
    // 'filemanager.gif',
    // 'filemounts.gif',
    // 'files.gif',
    // 'flash.gif',
    // 'folderC.gif',
    // 'folderCP.gif',
    // 'folderO.gif',
    // 'folderOP.gif',
    // 'folMinus.gif',
    // 'folPlus.gif',
    // 'form.gif',
    // 'forward_1.gif',
    // 'forward_4.gif',
    // 'forward_5.gif',
    // 'forward.gif',
    // 'hbg.jpg',
    // 'header_.gif',
    // 'headline.gif',
    // 'help.gif',
    // 'hints.gif',
    // 'home.gif',
    // 'important.gif',
    // 'index.gif',
    // 'install.gif',
    // 'left.gif',
    // 'loading.gif',
    // 'log.gif',
    // 'login.gif',
    // 'logo.gif',
    // 'logout.gif',
    // 'magnify.gif',
    // 'manager.gif',
    // 'member_.gif',
    // 'member.gif',
    // 'modMinus.gif',
    // 'modPlus.gif',
    // 'movel.gif',
    // 'mover.gif',
    // 'newfolder.gif',
    // 'new.gif',
    // 'news.gif',
    // 'ok.gif',
    // 'page.gif',
    // 'pagemounts.gif',
    // 'palBg.jpg',
    // 'palCollapsed.gif',
    // 'palOpen.gif',
    // 'pasteafter_.gif',
    // 'pasteafter.gif',
    // 'pasteinto_.gif',
    // 'pasteinto.gif',
    // 'pickcolor.gif',
    // 'pickfile.gif',
    // 'pickpage.gif',
    // 'placeholder.png',
    // 'preview.gif',
    // 'published.gif',
    // 'redirect_1.gif',
    // 'redirect_4.gif',
    // 'redirect_5.gif',
    // 'redirect.gif',
    // 'regular_1.gif',
    // 'regular_2.gif',
    // 'regular_3.gif',
    // 'regular_4.gif',
    // 'regular_5.gif',
    // 'regular_6.gif',
    // 'regular_7.gif',
    // 'regular.gif',
    // 'reload.gif',
    // 'right.gif',
    // 'root_1.gif',
    // 'root.gif',
    // 'rows.gif',
    // 'rss.gif',
    // 'select.gif',
    // 'settings.gif',
    // 'stop.png',
    // 'store.gif',
    // 'sync.gif',
    // 'tablewizard.gif',
    // 'template_editor.gif',
    // 'theme_import.gif',
    // 'themes.gif',
    // 'undo.gif',
    // 'unpublished.gif',
    // 'update.gif',
    // 'up.gif',
    // 'user_.gif',
    // 'user.gif',
    // 'wrap.gif'
];